name: Build APK

"on":
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-modern:
    name: Modern APK (Android 5.0+)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: ZIP ac
        run: |
          unzip TurkTV-MODERN-API21.zip -d modern
          INNER=$(ls modern/)
          echo "MDIR=modern/$INNER" >> $GITHUB_ENV

      - name: Gradle permission
        run: chmod +x ${{ env.MDIR }}/gradlew

      - name: Build
        working-directory: ${{ env.MDIR }}
        run: ./gradlew assembleDebug --no-daemon

      - name: APK bul
        run: |
          APK=$(find ${{ env.MDIR }} -name "*.apk" | head -1)
          cp "$APK" TurkTV-MODERN-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TurkTV-MODERN-API21
          path: TurkTV-MODERN-debug.apk
          retention-days: 30

  build-legacy:
    name: Legacy APK (Android 4.0.3+)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: ZIP ac
        run: |
          unzip TurkTV-LEGACY-API16.zip -d legacy
          INNER=$(ls legacy/)
          echo "LDIR=legacy/$INNER" >> $GITHUB_ENV

      - name: Gradle permission
        run: chmod +x ${{ env.LDIR }}/gradlew

      - name: Build
        working-directory: ${{ env.LDIR }}
        run: ./gradlew assembleDebug --no-daemon

      - name: APK bul
        run: |
          APK=$(find ${{ env.LDIR }} -name "*.apk" | head -1)
          cp "$APK" TurkTV-LEGACY-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TurkTV-LEGACY-API16
          path: TurkTV-LEGACY-debug.apk
          retention-days: 30
